name: build
'on':
    push:
        branches:
            - '*'
    pull_request:
        branches:
            - '*'
jobs:
    test:
        strategy:
            fail-fast: false
            matrix:
                php:
                    - 8.4
                    - 8.3
                    - 8.2
                    - 8.1
                    - 8
                    - 7.4
                    - 7.3
                    - 7.2
                laravel:
                    - 11.*
                    - 10.*
                    - 9.*
                    - 8.*
                    - 7.*
                    - 6.*
                stability:
                    - prefer-stable
                os:
                    - ubuntu-latest
        runs-on: '${{ matrix.os }}'
        name: >-
            P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability
            }} - ${{ matrix.os }}
        env:
            extensions: 'intl, json, mbstring, dom, curl, openssl, mcrypt'
        steps:
            -
                name: Checkout
                uses: actions/checkout@v2
            -
                name: Cache dependencies
                uses: actions/cache@v2
                with:
                    path: ~/.composer/cache/files
                    key: >-
                        dependencies-laravel-${{ matrix.laravel }}-php-${{
                        matrix.php }}-composer-${{ hashFiles('composer.json') }}
            -
                name: 'Setup PHP ${{ matrix.php }}'
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '${{ matrix.php }}'
                    extensions: '${{ env.extensions }}'
                    tools: composer
            -
                name: 'Setup Laravel ${{ matrix.laravel }}'
                run: >
                    composer require "laravel/framework:${{ matrix.laravel }}"
                    --no-interaction --no-update


                    # Definir o pacote testbench corretamente para cada versão
                    do Laravel

                    if [[ "${{ matrix.laravel }}" == "11." ]]; then
                      composer require "orchestra/testbench:^9.0" --dev --no-interaction --no-update
                    elif [[ "${{ matrix.laravel }}" == "10." ]]; then
                      composer require "orchestra/testbench:^8.0" --dev --no-interaction --no-update
                    elif [[ "${{ matrix.laravel }}" == "9." ]]; then
                      composer require "orchestra/testbench:^7.0" --dev --no-interaction --no-update
                    elif [[ "${{ matrix.laravel }}" == "8." ]]; then
                      composer require "orchestra/testbench:^6.23" --dev --no-interaction --no-update
                    fi


                    composer update --${{ matrix.stability }} --prefer-dist
                    --no-interaction --no-suggest
            -
                name: Run tests
                run: |
                    vendor/bin/phpunit --configuration phpunit.xml
