name: build

on:
    push:
        branches:
            - "main"
            - "master"
            - "dev"
    pull_request:
        branches:
            - "main"
            - "master"
            - "dev"

jobs:
    test:
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                php: [8.4, 8.3, 8.2, 8.1, 8.0, 7.4, 7.3, 7.2]
                laravel: [12.*, 11.*, 10.*, 9.*, 8.*, 7.*, 6.*]
                stability: [prefer-stable]
                include:
                    -   laravel: 12.*
                        testbench: 10.*
                    -   laravel: 11.*
                        testbench: 9.*
                    -   laravel: 10.*
                        testbench: 8.*
                    -   laravel: 9.*
                        testbench: 7.*
                    -   laravel: 8.*
                        testbench: 6.*
                    -   laravel: 7.*
                        testbench: 5.*
                    -   laravel: 6.*
                        testbench: 4.*
                exclude:
                    -   laravel: 12.*
                        php: 8.1
                    -   laravel: 12.*
                        php: 8.0
                    -   laravel: 12.*
                        php: 7.4
                    -   laravel: 12.*
                        php: 7.3
                    -   laravel: 12.*
                        php: 7.2
                    -   laravel: 11.*
                        php: 8.1
                    -   laravel: 11.*
                        php: 8.0
                    -   laravel: 11.*
                        php: 7.4
                    -   laravel: 11.*
                        php: 7.3
                    -   laravel: 11.*
                        php: 7.2
                    -   laravel: 10.*
                        php: 8.0
                    -   laravel: 10.*
                        php: 7.4
                    -   laravel: 10.*
                        php: 7.3
                    -   laravel: 10.*
                        php: 7.2
                    -   laravel: 9.*
                        php: 7.4
                    -   laravel: 9.*
                        php: 7.3
                    -   laravel: 9.*
                        php: 7.2
                    -   laravel: 8.*
                        php: 7.2

        runs-on: ${{ matrix.os }}
        name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Setup PHP ${{ matrix.php }}
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  ini-values: post_max_size=256M, max_execution_time=300
                  coverage: none

            - name: Setup Laravel ${{ matrix.laravel }}
              run: |
                  composer require illuminate/support:${{ matrix.laravel }} --no-update
                  composer require orchestra/testbench:${{ matrix.testbench }} --no-update
                  composer update --${{ matrix.stability }} --prefer-dist --no-progress --no-suggest --no-interaction

            - name: Run PHPUnit tests
              run: |
                  vendor/bin/phpunit --testdox
