name: Laravel CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: secret
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0' # ou qualquer versão que seu projeto use
          extensions: mbstring, bcmath, xml, ctype, json, curl, zip

      - name: Install Composer dependencies
        run: |
          composer install --prefer-dist --no-interaction

      - name: Generate application key
        run: php artisan key:generate

      - name: Set up the database
        run: |
          cp .env.example .env
          php artisan migrate --force

      - name: Run PHP-CS-Fixer
        run: composer php-cs-fixer-check

      - name: Run tests
        run: vendor/bin/phpunit --configuration phpunit.xml
